concurrent = 1

[[runners]]
name = "myRunner"
url = "http://gitlab/ci"
token = "glrt-xLc5fL31BRttpyrWK8Rz"
executor = "docker"
[runners.docker]
  tls_verify = false
  image = "docker"
  privileged = false
  disable_entrypoint_overwrite = false
  oom_kill_disable = false
  shm_size = 0
  allowed_pull_policies = ["always", "if-not-present"]
  volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
